### PR TITLE
Middleware::RescueErrors shall only run in production

### PR DESCRIPTION
**Pull request by tmaier**
Else its really hard to debug an error in one of the acceptance specs

### CODE REVIEW

**Comment by neilmiddleton** [comment]
I'm :-1: on this change as this would be of detriment to staging environments.
I think I'd would leave this as is, and let people change the template for their own use case.

Potentially this should be:

```
use Pliny::Middleware::RescueErrors unless %w{development test}.include? Config.rack_env
```

**Comment by tmaier** [comment]
Well this is not the first case of `Config.rack_env == "production"` in this file.
I'm also fine with `%w{development test}.include? Config.rack_env`. 

It's just wrong IMHO to suppress all errors in the test environment.

In the end, when someone wants to set up a staging environment, he needs anyway to look through the whole project and change all possible uses of `Config.rack_env` and `ENV['RACK_ENV']`

**Comment by mmcgrana** [comment]
IMO switches like this should have first-class config, not piggyback on 
global switches like rack_env. See http://12factor.net/config on grouping
vs. granular controls.

**Comment by brandur** [comment]
Agree with all of you! Haha.

@tmaier Maybe try something like `if Config.rescue_errors` with the default being true, but set to false in `.env.test`?

**Comment by tmaier** [comment]
Good point. I'm working on it

**Comment by tmaier** [comment]
I also considered to add 

``` ruby
instance_eval "def #{attr}?; return false if #{attr}.nil?; !!(#{attr} =~ /\Atrue|yes|on\z/i || #{attr}.to_i > 0) end", __FILE__, __LINE__
```

to `pliny/config_helpers`

Example

``` ruby
def rescue_errors?
  return false if rescue_errors.nil?
  !!(rescue_errors =~ /\Atrue|yes|on\z/i || rescue_errors.to_i > 0)
end
```

Then we could replace calls like `Config.rescue_errors.downcase == 'true'` with `Config.rescue_errors?`

**Comment by brandur** [comment]
Hah, nice! That's certainly a lot prettier. Thoughts on that one @mfine?

**Comment by mfine** [comment]
Nice, looks solid to me!

**Comment by neilmiddleton** [comment]
:+1:

**Comment by brandur** [comment]
Wicked. @tmaier Mind rebasing once more?

**Comment by tmaier** [comment]
Done.

What do you think about https://github.com/interagent/pliny-template/pull/108#issuecomment-45910189?

**Comment by brandur** [comment]
@tmaier Thanks! +1, let's try it.

**Comment by tmaier** [comment]
This will go into another pull request

**Pull request merged**
