### PR TITLE
Add Fine-style configuration file for access to ENV

### PR DESCRIPTION
**Pull request by brandur**
This is probably a little more controversial, but adds a configuration
file to make access of config vars easier -- similar to what we have in
API. It's not too obvious why this is useful at this scale, but it helps
clean things up a lot once a project gets to a certain size.

Thoughts on this one?

### CODE REVIEW

**Comment by mfine** [comment]
Yes! Wrap all accesses to `ENV` with declared config!

**Comment by pedro** [comment]
YES! Such a great pattern too, +1

**Comment by catsby** [comment]
This format:

``` ruby
optional \
  thing: value
```

is... new to me. Is that a common format? Are these `args` coming over as a hash?

**Comment by brandur** [comment]
@catsby It's probably bad style, hah. Same as `optional(thing: value)` which you'd receive as `def optional(opts = {})`. The backslash is just to prevent the interpreter from assuming the method invocation is finished by escaping the following newline.

**Comment by pedro** [comment]
Merging! Moving pliny to another org.

**Comment by catsby** [comment]
What new org?

**Comment by pedro** [comment]
@catsby https://github.com/12-oz/pliny

**Pull request merged**
