### PR TITLE
Copy docs from pliny README

### PR DESCRIPTION
**Pull request by jroes**
The guidance in the pliny README for getting started is relevant to projects generated from the template. This means that new projects starting from the template automatically get at least some documentation in their README on how to start the app, make changes, etc.

### CODE REVIEW

**Comment by brandur** [comment]
@jroes I'm a little worried that the two copies of the text will get out of sync pretty quickly. Any thoughts on what we could do to avoid that?

**Comment by jroes** [comment]
Yeah that's a good point, that thought crossed my mind for a sec.

What if we generated the README as part of `pliny-new`?

**Comment by brandur** [comment]
> What if we generated the README as part of `pliny-new`?

Sounds great! That way we could keep a more template-specific README in
the repo which just gets overwritten on a new app with something more
relevant. Do you want to give it a shot?

**Comment by jroes** [comment]
Closing in favor of interagent/pliny#83

**Pull request closed without merging**
