### PR TITLE
JSON Schema

### PR DESCRIPTION
**Pull request by brandur**
Leverage Prmd to start generating JSON Schemas for resources. Also adds a basic file structure for starting to manage a full schemata.

```
$ pliny-generate schema artists
created schema file ./docs/schema/schemata/artists.json
```

@pedro I know you expressed interest in a pure Ruby based solution for JSON Schema generation. Maybe we can bring this in for the time being until that project starts to come about?

### CODE REVIEW

**Comment by mmcgrana** [comment]
I think that we've previously preferred singular names for schemata files, right? In any event I think we should make the generated pattern here match the guidance in the [prmd Readme here](https://github.com/heroku/prmd#file-layout) (we may need to clarify the guidance in the latter).

/cc @geemus

**Comment by brandur** [comment]
@mmcgrana Great find! I noticed since that `Prmd.init` won't take a plural name (it will, but will append an extra "s" to endpoints within the file). I'm going to leave it here, but will have it fixed to use a singular name on the next pull.

**Comment by geemus** [comment]
@brandur yeah, just accepting singular and appending s naively has been fast/easy enough, may expand that eventually.

**Comment by brandur** [comment]
@geemus +1. Thanks!

Pulled scaffolding in from #51. Pulling this one in as well.

**Pull request merged**
