### PR TITLE
Override console process in Procfile

### PR DESCRIPTION
**Pull request by tmaier**

### CODE REVIEW

**Comment by pedro** [comment]
hmm interesting I don't usually have console in the `Procfile`, leaving it only for processes that I'd add to upstart/heroku/etc. What are the benefits of adding it here?

**Comment by neilmiddleton** [comment]
Yeah, I wouldn't do this either.  If you're running a console locally, spin it up locally also.  e.g:

```
foreman run bin/console
```

etc

**Comment by tmaier** [comment]
It's one of the default process types. If I use it, I would like to have access to my application and not to a default irb console.

https://github.com/heroku/heroku-buildpack-ruby/blob/master/lib/language_pack/ruby.rb#L73
(https://github.com/heroku/heroku-buildpack-ruby/blob/master/lib/language_pack/rails3.rb#L22)

**Comment by pedro** [comment]
Ah! That's an artifact of how Heroku used to work in the Bamboo days iirc, although I can see how it would be nice if every app I worked with had `console` defined.

@hone do you know more? is `heroku run console` something we still want to encourage?

**Comment by hone** [comment]
@pedro It's not something we've been trynig to encourage but like you're saying legacy that we have to have around from bamboo.

**Comment by tmaier** [comment]
Alright :)

**Pull request closed without merging**
