### PR TITLE
Use rollbar instead of honeybadger

### PR DESCRIPTION
**Pull request by gregburek**
New PR with new backing repo. Sorry.

### CODE REVIEW

**Comment by gregburek** [comment]
Related to issue #20

**Comment by brandur** [comment]
Cool, I'm up for giving it a shot. Thoughts @pedro?

**Comment by brandur** [comment]
Hey @gregburek, let's pull this in! Mind doing a rebase?

**Comment by gregburek** [comment]
Rebased and updated

**Comment by brandur** [comment]
@gregburek Thanks! We should still have a middleware in `lib/routes.rb` somewhere though right?

**Comment by gregburek** [comment]
Nope. It autoloads on require when it detects Rack via some magic :poop: https://github.com/rollbar/rollbar-gem/blob/master/lib/rollbar/rack.rb

**Comment by brandur** [comment]
Moar freedom patches! I tried to find a way a way to pull this in minus the crazy monkey patching, and it is technically possible, but might leave things in a fragile state (as soon as `configure` gets called, patches are applied). Unfortunately, the pieces are all pretty well intertwined.

It seems like there's demand for this one, so I'm pulling it in, but it would be nice to find a way to find a way to do this with less magic!

**Pull request merged**
