### PR TITLE
Use rake spec task provided by rspec

### PR DESCRIPTION
**Pull request by tmaier**
Every line not written is a line we don't need to maintain

Related: https://github.com/interagent/pliny/pull/89

### CODE REVIEW

**Comment by neilmiddleton** [comment]
This will break in production when especially isn't present.

**Comment by neilmiddleton** [comment]
S/especially/rspec 

Damn autocorrect

**Comment by pedro** [comment]
ugh, +1 :{ it's the one thing I hate about rspec, not sure about how we can handle it better.

**Comment by neilmiddleton** [comment]
Right now in most of my Pliny apps I'm doing this in the Rakefile:

``` ruby
# Add your rake tasks to lib/tasks!
Dir["./lib/tasks/*.rake"].each { |task| load task }

require 'pliny/tasks'

begin
  task :default => :spec
rescue LoadError
  # no rspec available
end
```

**Comment by brandur** [comment]
@neilmiddleton Wow, nice catch.

@tmaier That sounds like a fairly relevant concern. My gut reaction would probably be to leave this as is because a little bit of extra explicitness never really hurts in my experience. What do you think?

**Comment by pedro** [comment]
+1 for keeping the custom task for now! I at least added a little explanation for it here:
https://github.com/interagent/pliny/pull/104

Feel free to reply there or reopen the issue in Pliny!
Thanks Tobias.

**Pull request closed without merging**
