### PR TITLE
Add encode helper

### PR DESCRIPTION
**Pull request by tmaier**
My answer to https://github.com/interagent/http-api-design#keep-json-minified-in-all-responses

Shall this be in `Endpoints::Base` so that one can easily extend it or better as helper module in pliny?

Todo:
- [x] Update template in `pliny`

### CODE REVIEW

**Comment by brandur** [comment]
@tmaier You rock! Thanks for this :)

> Shall this be in Endpoints::Base so that one can easily extend it or better as helper module in pliny?

My vote would be to add this to something in the `Pliny::Helpers::` namespace. What do you think?

One other note: kind of along the trend of depending less on edge `RACK_ENV` behavior, what do you think about adding a dedicated `PRETTY_JSON` env var, which `.env.sample` sets to "true" by default?

**Comment by tmaier** [comment]
Alright. I will do it as said :)

**Comment by brandur** [comment]
Thanks :)

**Comment by tmaier** [comment]
Replaced by #132 and https://github.com/interagent/pliny/pull/69

**Pull request closed without merging**
