### PR TITLE
Adding foreman to the Gemfile

### PR DESCRIPTION
**Pull request by KensoDev**

### CODE REVIEW

**Comment by catsby** [comment]
Foreman likely belongs in a `:development` group in the `Gemfile`. Foreman is great for development use but I don't believe it's recommend for production environments.

**Comment by brandur** [comment]
+1 Clint! Avi, would mind you mind updating it to reside the `development` group?

Thanks a lot for sending this pull!

**Comment by KensoDev** [comment]
@brandur @catsby Sure, I'll update in a sec

**Comment by KensoDev** [comment]
@brandur @catsby Changed to be included in the `:development` group

**Comment by brandur** [comment]
Awesome, thank-you!

**Pull request merged**
