### PR TITLE
Add pliny-db-* commands

### PR DESCRIPTION
**Pull request by brandur**
Adds the following executables to Pliny based on the Rake tasks and miscellaneous executables that we had before in the template:
- `pliny-db-create` -- Creates dev and test databases.
- `pliny-db-drop` -- Drops dev and test databases.
- `pliny-db-dump` -- Dumps database schema to db/schema.sql.
- `pliny-db-load` -- Loads dev and test database schema from db/schema.sql.
- `pliny-db-merge` -- Resets databases, runs migrations, dumps schema, and removes migrations.
- `pliny-db-rollback` -- Rolls back a migration.

Also thinking about doing some parent namespacing think like `hk`'s approach to plugins too. So we might invoke these like `pliny db-create`.

/cc @mfine @pedro Does this look like the right way forward to you?

### CODE REVIEW

**Comment by pedro** [comment]
I like how this allows us to take code out of the app folder, but still think we should stick to the `rake` interface.

Mainly because it's already a standard – Sequel tried a similar approach with `sequel -m`, but in practice it seems like most people still go with the task. Rake also allows for task chaining: `rake db:create db:load db:migrate` only loads all the gems/environment once (as opposed to once per command, of course). Finally it also seems convenient to have all the administrative stuff available in Rake (including any app-specific stuff people might write) so you can see it all with `rake -T`, reuse them, etc.

So my vote would be to keep most of the code in Pliny like you're doing here, but making it available through rake tasks as opposed to bin files.

**Comment by mfine** [comment]
:+1: with @pedro here. I second everything he puts forth, plus the fact that all the specific ruby files end up with so much boiler plate in them.

**Comment by brandur** [comment]
+1 guys! Thanks a lot for great feedback here. I was definitely glad that I kept this one open so that we can discuss this a little bit while the project is still in its infancy.

Here are the two concerns I have with where we're going with the current system:
- Ambiguity: How does one decide when something should be implemented in bin/ versus in Rake? You'll notice that today we already have `bin/merge-schema` and `bin/generate`. Why are those executables instead of Rake tasks? In the latter's case, I'd probably say that it's because passing parameters into Rake is such a colossal pain (and often people will just resort to env vars instead of having something like `rake generate[model, SslEndpoint]`).
- Discoverability: Lack of command discovery through tab completion is a killer when using Rake. I know that there are some pretty smart tab completion scripts for Bash/ZSH now that will basically run `rake -T` to introspect a list of tasks and build a completion index, but this is slow and error prone at best. There's also no answers for parameters. Every time I'm rolling back in Rails I ask myself whether it's `STEP=2 bundle exec rake db:rollback` or `STEPS=2 bundle exec rake db:rollback` (with an extra "S"). More traditional CLI's solved these problems back in the 70's.
- Speed: Rake's start-up speed will follow that of your app's environment unless you resort to some pretty ugly conditional loading ([here's how I ended up doing it in the Heroku API](https://github.com/heroku/api/blob/master/Rakefile#L203) so that simple tasks like `db:migrate` can run without pulling in the entire environment). Pedro, you cited being able to chain Rake tasks as a feature, but I'd go as far as to call it an anti-pattern developed to work around Ruby's own conventions which often result in programs that start very slowly. To go over to the extreme, can you imagine someone arguing for an in-program chainable `grep` to avoid its start-up speed? Of course not, because it's fast! :) I think that by curating the requires inside our individual Pliny commands to make sure that we have the minimal set, we could ensure that they stay fast too.

All that said, I'm definitely willing to go in the direction that everyone else would like to see, and am definitely up for closing this pull out until such a time that we have a more clear way forward that everyone likes. Do you guys have any thoughts on how you'd think about handling the points above?

**Comment by sclasen** [comment]
If these commands are part of a gem, does that mean I could use the database related stuff to manage schema for a non ruby app?  sounds interesting if so...

**Comment by brandur** [comment]
@sclasen Yeah! These would get shared across the entire system as long as you have the Pliny gem installed system-wide.

**Comment by pedro** [comment]
Good stuff! Lets see:

> Ambiguity: How does one decide when something should be implemented in bin/ versus in Rake? 

Good point, my thinking is that bin/ is just to setup the app really. Anything to operate/maintain it should be a rake task. `merge-schema` is a great candidate for a rake task so it can be chained/etc. `generate` should clearly be a part of the standalone Pliny at some point (analogue to `rails new` / `rails generate`).

> Discoverability: Lack of command discovery through tab completion is a killer when using Rake.

+1, agreed this is a big downside for rake.

> Speed: Rake's start-up speed will follow that of your app's environment unless you resort to some pretty ugly conditional loading (here's how I ended up doing it in the Heroku API so that simple tasks like db:migrate can run without pulling in the entire environment). Pedro, you cited being able to chain Rake tasks as a feature, but I'd go as far as to call it an anti-pattern developed to work around Ruby's own conventions which often result in programs that start very slowly. To go over to the extreme, can you imagine someone arguing for an in-program chainable grep to avoid its start-up speed? Of course not, because it's fast! :) I think that by curating the requires inside our individual Pliny commands to make sure that we have the minimal set, we could ensure that they stay fast too.

It certainly would be better to make these files fast, but in practice people are apparently rewriting Ruby command line tools in other languages to achieve that. I think the biggest problem lies with requires and Rubygems, but we should probably talk to @geemus about this given his experience with the Heroku toolbelt. Wes, can we have a bin bundled with a gem that won't take 2s to boot? :}

**Comment by brandur** [comment]
> Good point, my thinking is that bin/ is just to setup the app really. Anything to operate/maintain it should be a rake task. merge-schema is a great candidate for a rake task so it can be chained/etc. generate should clearly be a part of the standalone Pliny at some point (analogue to rails new / rails generate).

Ah, +1! Just out of curiosity, why would you consider "generate" to be a Pliny executable candidate? It is designed to operate and maintain your project, which makes it seem like a solid Rake task candidate too.

> It certainly would be better to make these files fast, but in practice people are apparently rewriting Ruby command line tools in other languages to achieve that. I think the biggest problem lies with requires and Rubygems, but we should probably talk to @geemus about this given his experience with the Heroku toolbelt. Wes, can we have a bin bundled with a gem that won't take 2s to boot? :}

Hah, +1. Maybe we should include instructions to `cp vendor/pliny/bin/* /usr/local/bin/*`.

**Comment by geemus** [comment]
I think the slow part is actually `require 'rubygems'` more than anything else, as noted above. Outside of those requires, things are fairly fast (and it can be difficult to impossible to do much about that outside vendoring everything which is crappy in it's own right).

**Comment by brandur** [comment]
Talked this one over with Pedro and Fine and although Rake has problems, we'll revisit another time. Replaced by #56.

**Pull request closed without merging**
