### PR TITLE
Bump to rspec 3, use rspec-mocks instead of rr

### PR DESCRIPTION
**Pull request by pedro**
Following up to internal discussion, I personally went with rr for more flexibility in times I couldn't do things like `any_instance_of` with rspec, but a lot has changed since then.

Rspec 3 has been in beta for 6 months so it's probably good enough to upgrade. Overall I really like the changes/direction it's going, although slightly annoyed with the changes in expectations.

[Nice summary of the changes here](http://myronmars.to/n/dev-blog/2014/05/notable-changes-in-rspec-3)

### CODE REVIEW

**Comment by pedro** [comment]
Also added a trick I discussed with Brandur here so you don't have to do `def app` on every endpoint spec; instead a test support script will get it from the class being tested. For example:

``` ruby
describe Foobar
  it "responds with 200" do
    get "/" # <- this get will go to the class "Foobar"
  end
end
```

**Comment by brandur** [comment]
The RSpec mocking/stubbing syntax still seems way unnecessarily verbose to me, but +1 for killing it by default.

And wow, huge win on the spec'ed class trick for `Rack::Test`. I love it, haha.

**Comment by pedro** [comment]
@brandur thoughts on expectations? We'd also have to drop all the `should` in favor of `expects`. Wondering if we shouldn't just use minitest for asserting like we do in api...

**Comment by brandur** [comment]
@pedro Yeah! I love the idea of pulling in `expects` and enabling zero monkey-patch mode with `c.disable_monkey_patching!` by default.

I'm personally a big fan of `expect_with :minitest` as these RSpec expectations don't do much for me, but I this would probably be a more contentious change.

**Comment by hgmnz** [comment]
> couldn't do things like any_instance_of with rspec

I've always felt using `any_instance_of` as pointing at a bit of a smell, but I digress!

> We'd also have to drop all the should in favor of expects. 

+1 to that

``` ruby
    config.expect_with :rspec do |c|
      c.syntax = :expect
    end
```

**Comment by pedro** [comment]
In rspec 3 expect is already the only way to go (should is deprecated)! We're considering going with minitest though :D thoughts?

> I've always felt using any_instance_of as pointing at a bit of a smell, but I digress!

haha agreed. often a smell in a gem though :} although we do use for some of the client stubbing, hmm.

**Comment by brandur** [comment]
@pedro What do you think about pulling this in? We can tackle the `should` thing in a different issue.

**Comment by pedro** [comment]
+1! Merging.

Thanks folks

**Comment by gregburek** [comment]
@brandur regarding the `should` thing: https://github.com/yujinakayama/transpec

**Comment by brandur** [comment]
Whoah, this is handy :) We're not on RSpec 3 in API yet, but I kind of want to see what would happen if we ran this there ...

**Pull request merged**
