### PR TITLE
Extract gem

### PR DESCRIPTION
**Pull request by pedro**
- https://github.com/12-oz/pliny
- https://rubygems.org/gems/pliny

Fix #80

### CODE REVIEW

**Comment by pedro** [comment]
@gregburek @neilmiddleton what do you guys think / how much is this going to make your lives miserable seeing that you already have apps using it? :}

**Comment by gregburek** [comment]
This looks good. How does the internal to pliny use of `Bundler.require` interact with projects that are themselves calling pliny?

**Comment by brandur** [comment]
Wicked! Thanks Pedro!

@gregburek I think currently Bundler is only being called from the `pliny-generate` exectuable, which never gets required by the project itself (and as such, I don't think there will be any bundler conflicts). That said, we should probably just kill the use of bundler in there too.

**Comment by neilmiddleton** [comment]
This looks good to me - I switched over `support-api` [here](https://github.com/heroku/support-api/tree/pliny-gem).

One thing though - there's a bunch of dependencies that were in the original Gemfile (e.g `puma`, `sinatra-contrib`, `sequel-pg`, `oj` etc) that are probably dependencies of Pliny, but not that I can see in the gemspec.  Is this intentional?

**Comment by neilmiddleton** [comment]
actually, looking at it, I assume there's some other tweaks needed here.  For instance, I've blown away the local copy of `db.rake` and `environment.rake` for instance as they should be within the gem,  what's the best way of including those in my parent app?  Right now the tasks aren't getting dragged in.

**Comment by brandur** [comment]
Hey Neil, try `require "pliny/tasks"` in your project's `Rakefile`.

+1 on the Gem problem though. We probably need to shift a refactor that area a bit.

**Comment by neilmiddleton** [comment]
> try require "pliny/tasks" in your project's Rakefile.

Sure, it works fine - ideally this needs to automagically include itself in the app somehow.

**Comment by pedro** [comment]
Ok, OPENING THE GATES TO HELL!

**Pull request merged**
