### PR TITLE
Use rollbar to track exceptions (when configured)

### PR DESCRIPTION
**Pull request by mikehale**
I haven't tested this yet, but I think something along these lines is what would be needed to use rollbar.

Incidentally I'm wondering how this middleware would ever be called since the `RescueErrors` middleware catches, but does not re-raise exceptions.

### CODE REVIEW

**Comment by bjeanes** [comment]
I imagine that you'll have to set `raise_errors` config to `true` or put the `RescueErrors` middleware around the bugsnag middleware.

**Comment by brandur** [comment]
Wow, thanks a lot for taking a shot at this @mikehale!

I've written a few thoughts below. What do you think?
1. Like Bo said and you speculated yourself, frameworks like Sinatra will generally swallow errors in production and render them internally. You should still be rescuing errors like you have here, but you should also be looking for upstream hints from Sinatra or another similar application. Honeybadger uses the following to accomplish this:
   
   ```
       framework_exception = env['rack.exception'] || env['sinatra.error']
       if framework_exception
         env['honeybadger.error_id'] = notify_honeybadger(framework_exception, env)
       end
   ```
2. `RescueErrors` was originally intended mostly for capturing exceptions thrown from within the middleware stack (i.e. not raised by the application itself). I think it's a bit superfluous with something like what you've added here though. What do you think about merging both into a single middleware?
3. After merging, should we expand the tests for rescue errors to check for some of these error conditions? Maybe mock out the call to Rollbar and make sure that an exception set in `sinatra.error` is captured?

**Comment by mikehale** [comment]
Ah, so that's how it works. I'm uncertain as to how to proceed regarding rescuing errors now. What if rollbar/honeybadger/bugsnag is not enabled due to a missing api key? In that case would we need to fall back to something like RescueErrors?

**Comment by brandur** [comment]
@mikehale Yeah, at a high level, this top middleware should be rescuing errors all errors that manage to get back to it anyway (this is basically a layer of extra protection in case a middleware sends a failure back). If there's no API key, we should log the error normally, and do nothing else. Does this sound somewhat reasonable?

**Comment by gregburek** [comment]
The middleware is not necessary as rollbar inserts it's [own](https://github.com/rollbar/rollbar-gem/blob/master/lib/rollbar/middleware/rack/builder.rb) on [load](https://github.com/rollbar/rollbar-gem/blob/master/lib/rollbar/rack.rb#L3)

As far as I can tell, rollbar is also not loaded properly, yielding a silent failure on app boot. Also, sucker_punch is not in the gemfile, also yielding a silent failure of loading the sucker  

I have taken a simpler approach to adding rollbar with #76

**Comment by mikehale** [comment]
@gregburek :+1:, this PR was half-baked and I hadn't gotten a chance to come back to it. I think I also got a bit confused about what things should be vendored in pliny.

**Comment by mikehale** [comment]
Closed in favor of #76.

**Pull request closed without merging**
