### PR TITLE
bin/setup

### PR DESCRIPTION
**Pull request by pedro**
@brandur thoughts on ignoring `.env`? Don't remember the motivation for adding to the repo.

And hmm should we bring that thingy from API to also create and migrate the test db?

### CODE REVIEW

**Comment by brandur** [comment]
@pedro I did that because our `.env` doesn't yet have anything worthy of a secret, and we didn't have setup instructions in the README or a `bin/setup`. +1 for moving back to `.env.sample` and a script.

Definitely like the idea of running dev + test migrations simultaneously. IIRC, that was always a huge gotcha, even for developers who were experienced with the repo. The alternative would be to have a Rails-style "you have the following migrations that have not been run" that gets printed before the tests get run.

**Comment by pedro** [comment]
Awesome!

And eek, +1 for creating and migrating both then! Will bring that in.

**Comment by mfine** [comment]
@pedro hey, I captured this PR in https://github.com/12-oz/pliny/pull/28. Want to let that one supercede this one?

**Comment by pedro** [comment]
Absolutely! Thanks Mark!

**Pull request closed without merging**
