### PR TITLE
:WIP: Add SecureHeaders gem

### PR DESCRIPTION
**Pull request by catsby**
:construction: 

This pull request adds https://github.com/twitter/secureheaders to the project.

I think this mostly works, however, the `x_frame_options` doesn't do what I'd expect:

Before:

``` console
$ curl -i http://localhost:5000
HTTP/1.1 200 OK
Content-Type: text/html;charset=utf-8
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
Vary: Accept-Encoding
Request-Id: 56b34354-b3a8-4b79-82a7-e9dfc9179029
Content-Length: 6

hello.%
```

After:

``` console
$ curl -i http://localhost:5000
HTTP/1.1 200 OK
Content-Type: text/html;charset=utf-8
Content-Security-Policy-Report-Only: default-src 'none'; connect-src 'none'; font-src 'none'; frame-src 'none'; img-src 'none' data:; media-src 'none'; object-src 'none'; script-src 'none'; style-src 'none';
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
Vary: Accept-Encoding
Request-Id: 11005316-a923-42ee-b5a6-55af3091ac66
Content-Length: 6

hello.%
```

I'm not 100% sure all the headers are in there, and the `X-Frame-Options` still says `SAMEORIGIN`.

### CODE REVIEW

**Comment by catsby** [comment]
Updated to call all the methods explicitly. There's a method `ensure_security_headers` that _should_ do all this, but I get errors when calling it :( 

Comments/fixes welcome

**Comment by danp** [comment]
I think `ensure_security_headers` only works with rails.

The way you've set it up here is how I use it in other sinatra projects.

:+1:

**Comment by pedro** [comment]
The patch itself looks great to me! But I'm wary that most of these are only relevant for web pages and browsers, not applicable to pure JSON apis.

We discussed bringing some basic support for html to Pliny but decided to stick to pure JSON for now. If that's the case, are any of these middlewares still relevant? Or do you still think we should add it in case someone brings html things over?

/cc @brandur

**Comment by catsby** [comment]
> not applicable to pure JSON apis 

I missed this detail!
Sure, if something things like XSS protection doesn't make sense here we should not include it. 

Keep:
- `set_csp_header`
- `set_hsts_header`
- `set_x_content_type_options_header`

Remove:
-  `set_x_frame_options_header`
- `set_x_xss_protection_header`

I admit I don't fully understand [Content Security Policy](https://github.com/twitter/secureheaders#content-security-policy-csp)

**Comment by pedro** [comment]
Nice! :+1: :}

[From what I understand CSP is for XSS too](http://en.wikipedia.org/wiki/Content_Security_Policy). Shouldn't be relevant for JSON apis imho.

HSTS reminds me that we need to enforce https! But we can do that in another pull.

Thanks Clint!

**Comment by mfine** [comment]
Huge :+1: for enforcing `https`.

**Comment by mmcgrana** [comment]
Are there any practices here that we should also mention in our
API design guide, e.g. as things that we should also do for APIs
in other languages?

**Comment by pedro** [comment]
Still checking these headers, not positive they're relevant to pure JSON apis. Asking the security folks for their input.

But enforcing https is crucial, evidently. I like what we do at API, as suggested by @tmaher:

```
$ curl -n http://api.heroku.com/apps
{
  "id":"bad_request",
  "error":"Request rejected: The Heroku API supports HTTPS only. If you're on a shared network please consider resetting your credentials since they were sent without encryption."
}
```

**Comment by jacobian** [comment]
A few comments:
- A huge :+1: to enforcing HTTPS; there's no good reason to even have HTTP be an option. What API does is perfect, enforcing it here would be great.
- `X-Frame-Options: SAMEORIGIN` is OK, but `DENY` would probably be a better default. `SAMEORIGIN` will be acceptable in most cases, but in a few -- anything involving hosting user-supplied HTML -- it can bite. So `DENY` would be better.
- HSTS isn't that big a deal if you're not allowing HTTP (and most HTTP client libraries don't yet support HSTS anyway). However, it would provide another (potential) layer of security if for some reason the force-HTTP thing failed, so it's worth doing.
- CSP is still pretty experimental. I think it's probably not worth the effort at the moment.

**Comment by catsby** [comment]
- merged master
- dropped `x_xss_protection_header`
- added `rack-ssl` (only used in non-dev), enforces https

I wasn't sure _where_ to put `rack-ssl`; right now it's in "the app", and not in `vendor/`.

**Comment by catsby** [comment]
Updated `curl`(s): 

``` console
$ curl -I http://cts-pliny.herokuapp.com
HTTP/1.1 301 Moved Permanently
Content-Type: text/html
Location: https://cts-pliny.herokuapp.com/
Request-Id: a32a920a-3fe8-4eda-89d1-91eefacd12be
Vary: Accept-Encoding
Connection: keep-alive
```

and 

``` console
$ curl -I https://cts-pliny.herokuapp.com
HTTP/1.1 200 OK
Content-length: 6
Content-Security-Policy-Report-Only: default-src https://* 'self'; connect-src https://* 'self'; font-src https://* 'self'; frame-src https://* 'self'; img-src https://* data:; media-src https://* 'self'; object-src https://* 'self'; script-src https://* 'self'; style-src https://* 'self';
Content-Type: text/html;charset=utf-8
Request-Id: b5a511e9-79c1-492f-87af-f7d4581db8c0
Strict-Transport-Security: max-age=99; includeSubdomains
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Xss-Protection: 1; mode=block
Connection: keep-alive
```

**Comment by tmaher** [comment]
`Strict-Transport-Security: max-age=99; includeSubdomains`

As-is, this requests the client only enforce HTTPS only for the next 99 seconds.  Is that deliberate?

**Comment by catsby** [comment]
@tmaher that is configured in `config/initializers/secure_headers.rb`:

```
config.hsts = {:max_age => 99, :include_subdomains => true}
```

Deliberate only in that I copied that from the SecureHeaders site

**Comment by tmaher** [comment]
@catsby ah.  Assuming this is _only_ sent on `RACK_ENV=production`, I'd suggest 31536000 (one year), which is what all the cool kids seem to be recommending.

**Comment by catsby** [comment]
Updated. Any other thoughts or opinions here?

**Comment by pedro** [comment]
This looks great to me! Any thoughts @brandur ?

**Comment by brandur** [comment]
@catsby Wow man, great stuff! Nice discussion on this thread too; I certainly learnt a lot.

I'm a little surprised at how Twitter decided to build out this implementation; having controllers call into helpers is okay, but it seems to me that a middleware implementation would have been a lot more idiomatic (unless there's something I don't quite understand about how these work).

What do you think about creating a small Sinatra-based middleware and making the appropriate calls from inside it? This might have the advantages of a little less non-application noise in the base class, and give Pliny apps a way to enable or disable the headers by commenting in/out a single line:

``` ruby
module Pliny::Middleware
  class SecureHeaders < Sinatra::Base
    include SecureHeaders

    before do
      set_csp_header
      set_hsts_header
      set_x_frame_options_header
      set_x_content_type_options_header
    end
  end
end
```

``` ruby
Routes = Rack::Builder.new do
  ...
  use Pliny::Middleware::RequestStore, store: Pliny::RequestStore
  use Pliny::Middleware::SecureHeaders
  use Pliny::Middleware::Timeout, timeout: 45
  ...
end
```

What do you think?

**Comment by tmaier** [comment]
I like @brandur idea.

In the meantime #91 has been merged.
@catsby, could you please update your PR.

**Comment by pedro** [comment]
Hey! Closing this as we've moved the template back to Pliny, pliny-template is no longer in use.

**Pull request closed without merging**
