### PR TITLE
Serializer support

### PR DESCRIPTION
**Pull request by mfine**
https://github.com/12-oz/pliny/issues/38. Bring in serializer support.

### CODE REVIEW

**Comment by mfine** [comment]
WIP.

**Comment by mfine** [comment]
Simplified implementation put together. @brandur what do you think?

**Comment by brandur** [comment]
Sweet!

The one thing that I'm not a huge fan of with the current implementation (in API) is the switch on `if object.is_a?(Array)` inside the serialization routine. It just seems kind of weird that you have to go inspect the source to properly understand how it's working for either an array or object. I was almost thinking we should just move to using a `map` inside the list endpoint. Any thoughts on how we can improve that one?

**Comment by mfine** [comment]
:+1: on killing that - it's not buying much. Let just have a simple `serialize` method.

**Comment by brandur** [comment]
Looks great now! +1 for bring this in.

We should probably flesh some of this out in the generators too, but we can do that under a separate pull.

**Pull request merged**
